### ISSUE TITLE
1.0.7 vs. 1.1.0 and the mislabeling of 0.1 shrunkeness

### ISSUE THREAD

**Issue by Tiln1** [gigabit101/Shrink#38]
pixel = 1/16 of a block
The shrunk state in 1.0.7 was able to fit under a bed, i.e. <~3 pixels tall.
Using snow, the normal player height is 28-30 pixels tall,
while the 0.1 shrunk state in 1.1.0 is 6-8 pixels tall(~6.25 if I measure against a wall), which is more like 0.2 - 0.25.

This could be labeled as a bug or an enhancement, but I just want the ability to be 1.0.7's shrunk height tall.

After a restart, I am no longer able to select 0.1, but 0.2 is the same height as 0.1 was, probably something to do with that NBT editing stuff other issues talked about. 1.0/2.0 below have not changed.

**Comment by Tiln1** [comment]
Additionally, the 1.0 "shrunk" state is 32-34 pixels tall, more than the default,
And the 2.0 anti-shrunk state is 64-66 pixels tall, and more than 2 blocks wide.

**Comment by gigabit101** [comment]
Max and min-height can be set in the config file, I increased the min-height to prevent the x-ray issues from happening and set the default accordingly

**Comment by Tiln1** [comment]
The config specifies that the minimum minimum is 0.21, which is ya know, more than 0.1. Setting it to 0.1 anyway did not work. Additionally, my `Additionally` above was seemingly ignored.

**Comment by gigabit101** [comment]
I forgot that the config has a valid range and setting it below that range will not work.
I will NOT be changing this as it causes other issues with the camera etc.
UnShrinking resets you back to your default state, If your size is larger than expected then another mod is changing these defaults, This is not an issue with Shrink.

This issue is now locked as this is not changing.
