### ISSUE TITLE
request: adjust minimum size to 1/16 so that mod is compatible with Chisels and Bits

### ISSUE THREAD

**Issue by Nick-McKay** [gigabit101/Shrink#58]
With the minimum size being 0.21, collision with bits is very wonky

**Comment by gigabit101** [comment]
This value is in the config file and can be adjusted there, The default value is set to stop the camera causing x-ray issues

**Comment by Nick-McKay** [comment]
setting the value below 0.21 in the config just brings it back to 0.21

**Comment by James103** [comment]
> setting the value below 0.21 in the config just brings it back to 0.21

This is caused by the min value being `0.21` here: https://github.com/gigabit101/Shrink/blob/5bfa87386df25efcb02a4acad56c911c098e1f3a/src/main/java/net/gigabit101/shrink/config/ShrinkConfig.java#L48-L49

If this min value is to be reduced below 0.21, to e.g. 0.0625, a warning should be printed to chat if the current value of this setting is below 0.21 when a player joins a world.

**Comment by gigabit101** [comment]
I did forget I added a range however, I'm still not interested in allowing the player to become any smaller and allowing x-rays
